[project]
name = "ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.30",
    "langchain-experimental>=0.3.4",
    "langchain-mcp-adapters==0.1.1",
    "langchain-ollama==0.2.0",
    "langchain-openai>=0.3.35",
    "langgraph>=1.0.1",
    "langgraph-checkpoint-redis>=0.3.6",
    "redis>=5.0.0",
    "redisvl>=0.15.0",
    "mcp==1.9.0",
    "ollama==0.3.3",
    "openai>=2.50.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "langgraph-checkpoint-mongodb>=0.2.2",
    "psutil>=7.2.2",
    "pyautogui>=0.9.54",
]
[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
